# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title:  # Website name
baseurl: 'https://example.com/' # Website URL
copyright: '© 2021 Marc Sanjaume-Calvet'

############################
## LANGUAGE
############################

defaultContentLanguage: en

languages:
  en:
    languageName: English
    weight: 10

  ca:
    languageName: Catalan
    weight: 20

languages:
  en:
    languageName: English
    menu:
      main:

      - name: About
        url: '#about'
        weight: 10
      - name: Recent publications
        url: '#recentpublications'
        weight: 20
      - name: Courses
        url: /Courses/
        weight: 40
        identifier: "Courses"
      - name: Publications
        url: /Publications/
        weight: 30
        identifier : "Publications"
      - name: Current research
        url: /Research/
        weight: 50
        identifier : "Research"
      - name: Outreach
        url: /Outreach/
        weight: 60
        identifier : "Outreach"
      - name: CV
        url: https://msanjaume.netlify.app/uploads/resume.pdf
        weight: 70
      - name: Contact
        url: '#contact'
        weight: 80

languages:
  ca:
    languageName: Catalan
    menu:
      main:

      - name: Sobre mi
        url: '#about'
        weight: 10
      - name: Publicacions recents
        url: '#recentpublications'
        weight: 20
      - name: Docència
        url: /Courses/
        weight: 40
        identifier: "Courses"
      - name: Publicacions
        url: /Publications/
        weight: 30
        identifier : "Publications"
      - name: Recerca actual
        url: /Research/
        weight: 50
        identifier : "Research"
      - name: Mitjans
        url: /Outreach/
        weight: 60
        identifier : "Outreach"
      - name: CV
        url: https://msanjaume.netlify.app/uploads/resume.pdf
        weight: 70
      - name: Contacte
        url: '#Contacte'
        weight: 80


hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

blackfriday:
  angledQuotes: true
  fractions: false
  plainIDAnchors: true
  extensions:
    - hardLineBreak
