# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Me
    url: '#about'
    weight: 10
  - name: Courses
    url: '#Courses'
    weight: 20
  - name: Publications
    url: '#Publications'
    weight: 30
  - name: Outreach
    url: '#Outreach'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50
