# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: '#about'
    weight: 10
  - name: Courses
    url: Courses/
    weight: 30
  - name: Publications
    url: Publications/
    weight: 20
  - name: Current research
    url: Research/
    weight: 40
  - name: Datasets
    url: Datasets/
    weight: 50
  - name: Outreach
    url: Outreach/
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
